/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_calendar_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCalendarEventError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_calendar_appointments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCalendarAppointmentsError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_calendar_events`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCalendarEventsError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_calendar_appointment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostCalendarAppointmentError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_calendar_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostCalendarEventError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_calendar_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutCalendarEventError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Deletes an event in the user's calendar.
pub async fn delete_calendar_event(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, calendar_event_delete_request_body: Option<models::CalendarEventDeleteRequestBody>) -> Result<models::DeleteResponse, Error<DeleteCalendarEventError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_calendar_event_delete_request_body = calendar_event_delete_request_body;

    let uri_str = format!("{}/calendar/delete-event", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_calendar_event_delete_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCalendarEventError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of appointments filtered by context and context_id.
pub async fn get_calendar_appointments(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, context: &str, context_id: i32) -> Result<models::GetAppointmentsResponse, Error<GetCalendarAppointmentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_query_context = context;
    let p_query_context_id = context_id;

    let uri_str = format!("{}/calendar/get-appointments", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    req_builder = req_builder.query(&[("context", &p_query_context.to_string())]);
    req_builder = req_builder.query(&[("context_id", &p_query_context_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetAppointmentsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetAppointmentsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCalendarAppointmentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of calendar events.
pub async fn get_calendar_events(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str) -> Result<models::GetEventsResponse, Error<GetCalendarEventsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;

    let uri_str = format!("{}/calendar/get-events", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetEventsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetEventsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCalendarEventsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new appointment in the user's calendar. An appointment must be made within a specified context e.g. a 'Referral'
pub async fn post_calendar_appointment(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, calendar_appointment_create_request_body: Option<models::CalendarAppointmentCreateRequestBody>) -> Result<models::CreateResponse, Error<PostCalendarAppointmentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_calendar_appointment_create_request_body = calendar_appointment_create_request_body;

    let uri_str = format!("{}/calendar/add-appointment", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_calendar_appointment_create_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostCalendarAppointmentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new event in the user's calendar.
pub async fn post_calendar_event(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, calendar_event_create_request_body: Option<models::CalendarEventCreateRequestBody>) -> Result<models::CreateResponse, Error<PostCalendarEventError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_calendar_event_create_request_body = calendar_event_create_request_body;

    let uri_str = format!("{}/calendar/add-event", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_calendar_event_create_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostCalendarEventError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates an event in the user's calendar. For example, updating the 'status' from 'INVITED' to 'CONFIRMED' when a user accepts the invitation to an appointment.
pub async fn put_calendar_event(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, calendar_event_update_request_body: Option<models::CalendarEventUpdateRequestBody>) -> Result<models::UpdateResponse, Error<PutCalendarEventError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_calendar_event_update_request_body = calendar_event_update_request_body;

    let uri_str = format!("{}/calendar/update-event", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_calendar_event_update_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutCalendarEventError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

