/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_all_referrals`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllReferralsError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_single_referral`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSingleReferralError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_self_referral`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSelfReferralError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_referral_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateReferralStatusError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Returns a list of referrals.
pub async fn get_all_referrals(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str) -> Result<models::ReferralListResponse, Error<GetAllReferralsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;

    let uri_str = format!("{}/referrals/read-all", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ReferralListResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ReferralListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllReferralsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the requested referral.
pub async fn get_single_referral(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, id: &str) -> Result<models::ReferralSingleResponse, Error<GetSingleReferralError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_query_id = id;

    let uri_str = format!("{}/referrals/read-single", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    req_builder = req_builder.query(&[("id", &p_query_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ReferralSingleResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ReferralSingleResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSingleReferralError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new referral of type 'Self Referred' in the member's PDS.
pub async fn post_self_referral(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, self_referral_request_body: Option<models::SelfReferralRequestBody>) -> Result<models::CreateResponse, Error<PostSelfReferralError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_self_referral_request_body = self_referral_request_body;

    let uri_str = format!("{}/referrals/self-refer", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_self_referral_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSelfReferralError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates the status of a member's referral specified by id. For example, having been referred to a service, the status is set by default to 'Referred' and this route enables it to be updated to 'Accepted' or 'Rejected'
pub async fn update_referral_status(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, referral_status_update_request_body: Option<models::ReferralStatusUpdateRequestBody>) -> Result<models::UpdateResponse, Error<UpdateReferralStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_referral_status_update_request_body = referral_status_update_request_body;

    let uri_str = format!("{}/referrals/update-status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_referral_status_update_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateReferralStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

