/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_secure_message_conversation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSecureMessageConversationError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_secure_message_receive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSecureMessageReceiveError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_secure_message_send`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostSecureMessageSendError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Returns a list of secure messages that form part of a conversation.
pub async fn get_secure_message_conversation(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, conversation_id: &str) -> Result<models::SecureMessageConversationResponse, Error<GetSecureMessageConversationError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_query_conversation_id = conversation_id;

    let uri_str = format!("{}/secure-messages/conversation", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    req_builder = req_builder.query(&[("conversation_id", &p_query_conversation_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SecureMessageConversationResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SecureMessageConversationResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSecureMessageConversationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new received message in the member's PDS.
pub async fn post_secure_message_receive(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, secure_message_receive_request: Option<models::SecureMessageReceiveRequest>) -> Result<models::CreateResponse, Error<PostSecureMessageReceiveError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_secure_message_receive_request = secure_message_receive_request;

    let uri_str = format!("{}/secure-messages/receive", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_secure_message_receive_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSecureMessageReceiveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates a new sent message in the member's PDS.
pub async fn post_secure_message_send(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, secure_message_send_request: Option<models::SecureMessageSendRequest>) -> Result<models::CreateResponse, Error<PostSecureMessageSendError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_body_secure_message_send_request = secure_message_send_request;

    let uri_str = format!("{}/secure-messages/send", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_secure_message_send_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostSecureMessageSendError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

