/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_timeline`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimelineError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_timeline_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimelineItemError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Returns a list of timeline items which includes: referrals, calendar events and secure messages.
pub async fn get_timeline(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str) -> Result<models::TimelineResponse, Error<GetTimelineError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;

    let uri_str = format!("{}/timeline", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TimelineResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TimelineResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTimelineError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a single timeline item based on feature block and feature block id requested e.g. a 'referral' with id 123.
pub async fn get_timeline_item(configuration: &configuration::Configuration, connection_token: &str, uid: &str, con_id: &str, feature_block: &str, feature_block_id: i32) -> Result<models::TimelineSingleItemResponse, Error<GetTimelineItemError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_connection_token = connection_token;
    let p_query_uid = uid;
    let p_query_con_id = con_id;
    let p_query_feature_block = feature_block;
    let p_query_feature_block_id = feature_block_id;

    let uri_str = format!("{}/timeline/single-item", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("uid", &p_query_uid.to_string())]);
    req_builder = req_builder.query(&[("con_id", &p_query_con_id.to_string())]);
    req_builder = req_builder.query(&[("feature_block", &p_query_feature_block.to_string())]);
    req_builder = req_builder.query(&[("feature_block_id", &p_query_feature_block_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("Connection-Token", p_header_connection_token.to_string());
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TimelineSingleItemResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TimelineSingleItemResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetTimelineItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

