/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddReferralResponse : Response from creating a referral via /referrals/add. The shape varies depending on member connection status: 'complete' when the member is already connected to the remote DSSA, 'pending' with url/qr when the member is present but not connected, and 'pending' with message when the member is not present and has been notified.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddReferralResponse {
    /// Indicates success
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    /// 'complete' when the member is already connected to the remote DSSA; 'pending' when the member needs to complete the FTC flow
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Present only when status is 'pending'. Describes the pending action taken.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// FTC URL the member should be redirected to. Present only when status is 'pending' and member_present is true.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// QR code data URI for the FTC URL. Present only when status is 'pending' and member_present is true.
    #[serde(rename = "qr", skip_serializing_if = "Option::is_none")]
    pub qr: Option<String>,
    /// ID of the newly created referral
    #[serde(rename = "referral_id", skip_serializing_if = "Option::is_none")]
    pub referral_id: Option<i32>,
}

impl AddReferralResponse {
    /// Response from creating a referral via /referrals/add. The shape varies depending on member connection status: 'complete' when the member is already connected to the remote DSSA, 'pending' with url/qr when the member is present but not connected, and 'pending' with message when the member is not present and has been notified.
    pub fn new() -> AddReferralResponse {
        AddReferralResponse {
            success: None,
            status: None,
            message: None,
            url: None,
            qr: None,
            referral_id: None,
        }
    }
}
/// 'complete' when the member is already connected to the remote DSSA; 'pending' when the member needs to complete the FTC flow
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Complete
    }
}

