/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddReferralRequestBody : Fields for initiating a referral to a remote DSSA via /referrals/add
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddReferralRequestBody {
    /// UUIDv4 of the remote DSSA the referral is being made to
    #[serde(rename = "remote_dssa_uuid")]
    pub remote_dssa_uuid: uuid::Uuid,
    /// Whether the member is present to complete the FTC flow. If true, an FTC URL is returned for immediate redirect. If false, a notification is sent to the member.
    #[serde(rename = "member_present")]
    pub member_present: bool,
    /// URL the member is redirected to after completing the FTC flow
    #[serde(rename = "return_to")]
    pub return_to: String,
    #[serde(rename = "referral_data")]
    pub referral_data: Box<models::AddReferralData>,
}

impl AddReferralRequestBody {
    /// Fields for initiating a referral to a remote DSSA via /referrals/add
    pub fn new(remote_dssa_uuid: uuid::Uuid, member_present: bool, return_to: String, referral_data: models::AddReferralData) -> AddReferralRequestBody {
        AddReferralRequestBody {
            remote_dssa_uuid,
            member_present,
            return_to,
            referral_data: Box::new(referral_data),
        }
    }
}

