/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthErrorResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::AuthErrorResponseError>>,
}

impl AuthErrorResponse {
    pub fn new() -> AuthErrorResponse {
        AuthErrorResponse {
            error: None,
        }
    }
}

