/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CalendarEventCommonRequestBodyFields : Common fields shared across all calendar event types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarEventCommonRequestBodyFields {
    /// Title of the event
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Detailed description of the event
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Start date and time as Unix timestamp
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<i64>,
    /// End date and time as Unix timestamp
    #[serde(rename = "end_timestamp", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<i64>,
    /// Status of the event
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Creator of the event
    #[serde(rename = "organiser", skip_serializing_if = "Option::is_none")]
    pub organiser: Option<String>,
    /// Person attending the event
    #[serde(rename = "attendee", skip_serializing_if = "Option::is_none")]
    pub attendee: Option<String>,
    /// Event location
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

impl CalendarEventCommonRequestBodyFields {
    /// Common fields shared across all calendar event types
    pub fn new() -> CalendarEventCommonRequestBodyFields {
        CalendarEventCommonRequestBodyFields {
            title: None,
            description: None,
            start_timestamp: None,
            end_timestamp: None,
            status: None,
            organiser: None,
            attendee: None,
            location: None,
        }
    }
}
/// Status of the event
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "INVITED")]
    Invited,
    #[serde(rename = "TENTATIVE")]
    Tentative,
    #[serde(rename = "CONFIRMED")]
    Confirmed,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Invited
    }
}

