/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CalendarEventDeleteRequestBody : Fields for deleting a calendar event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarEventDeleteRequestBody {
    /// ID of the calendar-event to be deleted
    #[serde(rename = "id")]
    pub id: i32,
}

impl CalendarEventDeleteRequestBody {
    /// Fields for deleting a calendar event.
    pub fn new(id: i32) -> CalendarEventDeleteRequestBody {
        CalendarEventDeleteRequestBody {
            id,
        }
    }
}

