/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CalendarAppointmentCreateRequestBody : Fields for creating a calendar event of type 'Appointment'
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarAppointmentCreateRequestBody {
    /// Title of the event
    #[serde(rename = "title")]
    pub title: String,
    /// Detailed description of the event
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Start date and time as Unix timestamp
    #[serde(rename = "start_timestamp")]
    pub start_timestamp: i64,
    /// End date and time as Unix timestamp
    #[serde(rename = "end_timestamp")]
    pub end_timestamp: i64,
    /// Status of the event
    #[serde(rename = "status")]
    pub status: Status,
    /// Creator of the event
    #[serde(rename = "organiser", skip_serializing_if = "Option::is_none")]
    pub organiser: Option<String>,
    /// Person attending the event
    #[serde(rename = "attendee", skip_serializing_if = "Option::is_none")]
    pub attendee: Option<String>,
    /// Event location
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// The context the appointment belongs to e.g. a referral
    #[serde(rename = "context")]
    pub context: Context,
    /// The id of the specific context record that this appointment relates to e.g. the referral id
    #[serde(rename = "context_id")]
    pub context_id: i32,
}

impl CalendarAppointmentCreateRequestBody {
    /// Fields for creating a calendar event of type 'Appointment'
    pub fn new(title: String, start_timestamp: i64, end_timestamp: i64, status: Status, context: Context, context_id: i32) -> CalendarAppointmentCreateRequestBody {
        CalendarAppointmentCreateRequestBody {
            title,
            description: None,
            start_timestamp,
            end_timestamp,
            status,
            organiser: None,
            attendee: None,
            location: None,
            context,
            context_id,
        }
    }
}
/// Status of the event
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "INVITED")]
    Invited,
    #[serde(rename = "TENTATIVE")]
    Tentative,
    #[serde(rename = "CONFIRMED")]
    Confirmed,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Invited
    }
}
/// The context the appointment belongs to e.g. a referral
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Context {
    #[serde(rename = "referral")]
    Referral,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Context {
    fn default() -> Context {
        Self::Referral
    }
}

