/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralListResponse : Response containing a list of referrals
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralListResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    #[serde(rename = "referrals", skip_serializing_if = "Option::is_none")]
    pub referrals: Option<Vec<models::ReferralListResponseReferralsInner>>,
}

impl ReferralListResponse {
    /// Response containing a list of referrals
    pub fn new() -> ReferralListResponse {
        ReferralListResponse {
            success: None,
            referrals: None,
        }
    }
}

