/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralSingleResponse : Response containing a single referral (requires query parameter 'id')
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralSingleResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    #[serde(rename = "referral", skip_serializing_if = "Option::is_none")]
    pub referral: Option<Box<models::ReferralSingleResponseReferral>>,
}

impl ReferralSingleResponse {
    /// Response containing a single referral (requires query parameter 'id')
    pub fn new() -> ReferralSingleResponse {
        ReferralSingleResponse {
            success: None,
            referral: None,
        }
    }
}

