/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralCommonRequestBodyFields : Common fields shared across all referral types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralCommonRequestBodyFields {
    /// ID of the service being referred to
    #[serde(rename = "service_id", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<i32>,
    /// Background information about the referree
    #[serde(rename = "referree_background", skip_serializing_if = "Option::is_none")]
    pub referree_background: Option<String>,
    /// Requirements of the referree
    #[serde(rename = "referree_requirements", skip_serializing_if = "Option::is_none")]
    pub referree_requirements: Option<String>,
    #[serde(rename = "referree_availability", skip_serializing_if = "Option::is_none")]
    pub referree_availability: Option<Box<models::ReferralCommonRequestBodyFieldsReferreeAvailability>>,
    /// Name of the person making the referral
    #[serde(rename = "referrer_name", skip_serializing_if = "Option::is_none")]
    pub referrer_name: Option<String>,
    /// Name of the service
    #[serde(rename = "service_name", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    /// Description of the service
    #[serde(rename = "service_description", skip_serializing_if = "Option::is_none")]
    pub service_description: Option<String>,
    /// URL of the service
    #[serde(rename = "service_url", skip_serializing_if = "Option::is_none")]
    pub service_url: Option<String>,
    /// Email address of the service
    #[serde(rename = "service_email", skip_serializing_if = "Option::is_none")]
    pub service_email: Option<String>,
    /// Contact number for the service
    #[serde(rename = "contact_number", skip_serializing_if = "Option::is_none")]
    pub contact_number: Option<String>,
    /// Internal memo or notes
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// Start time as a Unix timestamp
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
}

impl ReferralCommonRequestBodyFields {
    /// Common fields shared across all referral types
    pub fn new() -> ReferralCommonRequestBodyFields {
        ReferralCommonRequestBodyFields {
            service_id: None,
            referree_background: None,
            referree_requirements: None,
            referree_availability: None,
            referrer_name: None,
            service_name: None,
            service_description: None,
            service_url: None,
            service_email: None,
            contact_number: None,
            memo: None,
            start_time: None,
        }
    }
}

