/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralStatusUpdateRequestBody : Fields for updating the status of a referral (e.g. from 'Referred' to 'Accepted')
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralStatusUpdateRequestBody {
    /// ID of the referral to be updated
    #[serde(rename = "id")]
    pub id: i32,
    /// Status the referral is to be updated to
    #[serde(rename = "status")]
    pub status: Status,
}

impl ReferralStatusUpdateRequestBody {
    /// Fields for updating the status of a referral (e.g. from 'Referred' to 'Accepted')
    pub fn new(id: i32, status: Status) -> ReferralStatusUpdateRequestBody {
        ReferralStatusUpdateRequestBody {
            id,
            status,
        }
    }
}
/// Status the referral is to be updated to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Referred")]
    Referred,
    #[serde(rename = "In Progress")]
    InProgress,
    #[serde(rename = "Accepted")]
    Accepted,
    #[serde(rename = "Rejected")]
    Rejected,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Referred
    }
}

