/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferralCommonRequestBodyFieldsReferreeAvailability : Availability of the referree. If not provided, defaults to empty AM/PM arrays.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralCommonRequestBodyFieldsReferreeAvailability {
    /// Morning availability slots
    #[serde(rename = "AM", skip_serializing_if = "Option::is_none")]
    pub am: Option<Vec<String>>,
    /// Afternoon availability slots
    #[serde(rename = "PM", skip_serializing_if = "Option::is_none")]
    pub pm: Option<Vec<String>>,
}

impl ReferralCommonRequestBodyFieldsReferreeAvailability {
    /// Availability of the referree. If not provided, defaults to empty AM/PM arrays.
    pub fn new() -> ReferralCommonRequestBodyFieldsReferreeAvailability {
        ReferralCommonRequestBodyFieldsReferreeAvailability {
            am: None,
            pm: None,
        }
    }
}

