/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecureMessageReceiveRequest : Request to receive a secure message
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecureMessageReceiveRequest {
    /// Content of the message
    #[serde(rename = "message_content")]
    pub message_content: String,
    /// ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context.
    #[serde(rename = "conversation_id")]
    pub conversation_id: String,
    /// Sender user ID
    #[serde(rename = "message_from")]
    pub message_from: String,
}

impl SecureMessageReceiveRequest {
    /// Request to receive a secure message
    pub fn new(message_content: String, conversation_id: String, message_from: String) -> SecureMessageReceiveRequest {
        SecureMessageReceiveRequest {
            message_content,
            conversation_id,
            message_from,
        }
    }
}

