/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecureMessage : A single message within a conversation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecureMessage {
    /// Message ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Conversation identifier
    #[serde(rename = "conversation_id", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Recipient of the message (present on sent messages)
    #[serde(rename = "message_to", skip_serializing_if = "Option::is_none")]
    pub message_to: Option<String>,
    /// Sender of the message (present on received messages)
    #[serde(rename = "message_from", skip_serializing_if = "Option::is_none")]
    pub message_from: Option<String>,
    /// Timestamp when message was sent
    #[serde(rename = "time_sent", skip_serializing_if = "Option::is_none")]
    pub time_sent: Option<String>,
    /// Timestamp when message was received
    #[serde(rename = "time_received", skip_serializing_if = "Option::is_none")]
    pub time_received: Option<String>,
    /// Content of the message
    #[serde(rename = "message_content", skip_serializing_if = "Option::is_none")]
    pub message_content: Option<String>,
    /// Message status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl SecureMessage {
    /// A single message within a conversation
    pub fn new() -> SecureMessage {
        SecureMessage {
            id: None,
            conversation_id: None,
            message_to: None,
            message_from: None,
            time_sent: None,
            time_received: None,
            message_content: None,
            status: None,
        }
    }
}
/// Message status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "received")]
    Received,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Sent
    }
}

