/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecureMessageSendRequest : Request to send a secure message
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecureMessageSendRequest {
    /// Content of the message
    #[serde(rename = "message_content")]
    pub message_content: String,
    /// ID of the conversation formatted like {context}-{context_id} where context is e.g. 'referral' and context_id is the id of the specifc record in that context.
    #[serde(rename = "conversation_id")]
    pub conversation_id: String,
    /// Recipient user ID
    #[serde(rename = "message_to")]
    pub message_to: String,
}

impl SecureMessageSendRequest {
    /// Request to send a secure message
    pub fn new(message_content: String, conversation_id: String, message_to: String) -> SecureMessageSendRequest {
        SecureMessageSendRequest {
            message_content,
            conversation_id,
            message_to,
        }
    }
}

