/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TimelineResponseTimelineInner {
    TimelineResponseTimelineInnerOneOf(Box<models::TimelineResponseTimelineInnerOneOf>),
    TimelineResponseTimelineInnerOneOf1(Box<models::TimelineResponseTimelineInnerOneOf1>),
    TimelineResponseTimelineInnerOneOf2(Box<models::TimelineResponseTimelineInnerOneOf2>),
}

impl Default for TimelineResponseTimelineInner {
    fn default() -> Self {
        Self::TimelineResponseTimelineInnerOneOf(Default::default())
    }
}

