/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineSingleItemResponse : Response containing a single timeline item, which can be a referral, secure message, or calendar event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineSingleItemResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    #[serde(rename = "timeline_item", skip_serializing_if = "Option::is_none")]
    pub timeline_item: Option<Box<models::TimelineSingleItemResponseTimelineItem>>,
}

impl TimelineSingleItemResponse {
    /// Response containing a single timeline item, which can be a referral, secure message, or calendar event
    pub fn new() -> TimelineSingleItemResponse {
        TimelineSingleItemResponse {
            success: None,
            timeline_item: None,
        }
    }
}

