/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineItemSecureMessage : A single timeline item representing a secure message
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineItemSecureMessage {
    /// Type of feature block this timeline item belongs to
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    /// ID of the feature block
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<i32>,
    /// Formatted start timestamp for display
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
    /// Raw timestamp of the timeline item
    #[serde(rename = "item_timestamp", skip_serializing_if = "Option::is_none")]
    pub item_timestamp: Option<i64>,
    #[serde(rename = "created_timestamp", skip_serializing_if = "Option::is_none")]
    pub created_timestamp: Option<i64>,
    #[serde(rename = "updated_timestamp", skip_serializing_if = "Option::is_none")]
    pub updated_timestamp: Option<i64>,
    /// Conversation identifier
    #[serde(rename = "conversation_id", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// Timestamp when message was sent
    #[serde(rename = "time_sent", skip_serializing_if = "Option::is_none")]
    pub time_sent: Option<String>,
    /// Timestamp when message was received
    #[serde(rename = "time_received", skip_serializing_if = "Option::is_none")]
    pub time_received: Option<String>,
    /// Sender of the message (present on received messages)
    #[serde(rename = "message_from", skip_serializing_if = "Option::is_none")]
    pub message_from: Option<String>,
    /// Recipient of the message (present on sent messages)
    #[serde(rename = "message_to", skip_serializing_if = "Option::is_none")]
    pub message_to: Option<String>,
    /// Content of the message
    #[serde(rename = "message_content", skip_serializing_if = "Option::is_none")]
    pub message_content: Option<String>,
}

impl TimelineItemSecureMessage {
    /// A single timeline item representing a secure message
    pub fn new() -> TimelineItemSecureMessage {
        TimelineItemSecureMessage {
            feature_block: None,
            feature_block_id: None,
            start_timestamp: None,
            item_timestamp: None,
            created_timestamp: None,
            updated_timestamp: None,
            conversation_id: None,
            time_sent: None,
            time_received: None,
            message_from: None,
            message_to: None,
            message_content: None,
        }
    }
}

