/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineResponse : Response containing a mixed timeline of calendar events, referrals, and secure messages
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    /// Array of timeline items, which can be calendar events, referrals, or secure messages
    #[serde(rename = "timeline", skip_serializing_if = "Option::is_none")]
    pub timeline: Option<Vec<models::TimelineResponseTimelineInner>>,
}

impl TimelineResponse {
    /// Response containing a mixed timeline of calendar events, referrals, and secure messages
    pub fn new() -> TimelineResponse {
        TimelineResponse {
            success: None,
            timeline: None,
        }
    }
}

