/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineResponseTimelineInnerOneOf2 : Calendar event item
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineResponseTimelineInnerOneOf2 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<String>,
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
    #[serde(rename = "item_timestamp", skip_serializing_if = "Option::is_none")]
    pub item_timestamp: Option<i32>,
    #[serde(rename = "end_timestamp", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "organiser", skip_serializing_if = "Option::is_none")]
    pub organiser: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "duration_string", skip_serializing_if = "Option::is_none")]
    pub duration_string: Option<String>,
    #[serde(rename = "duration_of_event", skip_serializing_if = "Option::is_none")]
    pub duration_of_event: Option<f64>,
}

impl TimelineResponseTimelineInnerOneOf2 {
    /// Calendar event item
    pub fn new() -> TimelineResponseTimelineInnerOneOf2 {
        TimelineResponseTimelineInnerOneOf2 {
            id: None,
            feature_block: None,
            feature_block_id: None,
            start_timestamp: None,
            item_timestamp: None,
            end_timestamp: None,
            title: None,
            location: None,
            organiser: None,
            description: None,
            status: None,
            duration_string: None,
            duration_of_event: None,
        }
    }
}

