/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineSingleItemResponseTimelineItem : The timeline item, which can be one of multiple types, returned as an object
/// The timeline item, which can be one of multiple types, returned as an object
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TimelineSingleItemResponseTimelineItem {
    TimelineItemReferral(Box<models::TimelineItemReferral>),
    TimelineItemSecureMessage(Box<models::TimelineItemSecureMessage>),
    TimelineItemCalendarEvent(Box<models::TimelineItemCalendarEvent>),
}

impl Default for TimelineSingleItemResponseTimelineItem {
    fn default() -> Self {
        Self::TimelineItemReferral(Default::default())
    }
}

