/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineResponseTimelineInnerOneOf1 : Secure message item
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineResponseTimelineInnerOneOf1 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<String>,
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
    #[serde(rename = "item_timestamp", skip_serializing_if = "Option::is_none")]
    pub item_timestamp: Option<i32>,
    #[serde(rename = "created_timestamp", skip_serializing_if = "Option::is_none")]
    pub created_timestamp: Option<i32>,
    #[serde(rename = "message_from", skip_serializing_if = "Option::is_none")]
    pub message_from: Option<String>,
    #[serde(rename = "message_to", skip_serializing_if = "Option::is_none")]
    pub message_to: Option<String>,
    #[serde(rename = "message_content", skip_serializing_if = "Option::is_none")]
    pub message_content: Option<String>,
}

impl TimelineResponseTimelineInnerOneOf1 {
    /// Secure message item
    pub fn new() -> TimelineResponseTimelineInnerOneOf1 {
        TimelineResponseTimelineInnerOneOf1 {
            id: None,
            feature_block: None,
            feature_block_id: None,
            start_timestamp: None,
            item_timestamp: None,
            created_timestamp: None,
            message_from: None,
            message_to: None,
            message_content: None,
        }
    }
}

