/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineItemReferral : A single timeline item representing a referral
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineItemReferral {
    /// Type of feature block this timeline item belongs to
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    /// ID of the feature block record i.e. the referral id
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<i32>,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// The context within which this record was created i.e. the specific connection
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "created_timestamp", skip_serializing_if = "Option::is_none")]
    pub created_timestamp: Option<i64>,
    #[serde(rename = "updated_timestamp", skip_serializing_if = "Option::is_none")]
    pub updated_timestamp: Option<i64>,
    /// The id of the service that the referral relates to
    #[serde(rename = "service_id", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<i32>,
    #[serde(rename = "service_name", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "service_description", skip_serializing_if = "Option::is_none")]
    pub service_description: Option<String>,
    #[serde(rename = "service_url", skip_serializing_if = "Option::is_none")]
    pub service_url: Option<String>,
    #[serde(rename = "service_email", skip_serializing_if = "Option::is_none")]
    pub service_email: Option<String>,
    #[serde(rename = "contact_name", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<String>,
    #[serde(rename = "contact_title", skip_serializing_if = "Option::is_none")]
    pub contact_title: Option<String>,
    #[serde(rename = "contact_number", skip_serializing_if = "Option::is_none")]
    pub contact_number: Option<String>,
    #[serde(rename = "referrer_name", skip_serializing_if = "Option::is_none")]
    pub referrer_name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<i64>,
    #[serde(rename = "is_processed", skip_serializing_if = "Option::is_none")]
    pub is_processed: Option<bool>,
    #[serde(rename = "complete_time", skip_serializing_if = "Option::is_none")]
    pub complete_time: Option<i32>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    #[serde(rename = "referree_background", skip_serializing_if = "Option::is_none")]
    pub referree_background: Option<String>,
    #[serde(rename = "referree_requirements", skip_serializing_if = "Option::is_none")]
    pub referree_requirements: Option<String>,
    /// Availability of the referree in AM/PM slots
    #[serde(rename = "referree_availability", skip_serializing_if = "Option::is_none")]
    pub referree_availability: Option<serde_json::Value>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
}

impl TimelineItemReferral {
    /// A single timeline item representing a referral
    pub fn new() -> TimelineItemReferral {
        TimelineItemReferral {
            feature_block: None,
            feature_block_id: None,
            instance: None,
            source: None,
            created_timestamp: None,
            updated_timestamp: None,
            service_id: None,
            service_name: None,
            service_description: None,
            service_url: None,
            service_email: None,
            contact_name: None,
            contact_title: None,
            contact_number: None,
            referrer_name: None,
            status: None,
            external_id: None,
            start_time: None,
            end_time: None,
            is_processed: None,
            complete_time: None,
            memo: None,
            duration: None,
            referree_background: None,
            referree_requirements: None,
            referree_availability: None,
            r#type: None,
            start_timestamp: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Referred")]
    Referred,
    #[serde(rename = "In Progress")]
    InProgress,
    #[serde(rename = "Accepted")]
    Accepted,
    #[serde(rename = "Rejected")]
    Rejected,
    #[serde(rename = "unknown_default_open_api")]
    UnknownDefaultOpenApi,
}

impl Default for Status {
    fn default() -> Status {
        Self::Referred
    }
}

