/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineResponseTimelineInnerOneOf : Referral item
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineResponseTimelineInnerOneOf {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<String>,
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
    #[serde(rename = "item_timestamp", skip_serializing_if = "Option::is_none")]
    pub item_timestamp: Option<i32>,
    #[serde(rename = "service_description", skip_serializing_if = "Option::is_none")]
    pub service_description: Option<String>,
    #[serde(rename = "service_name", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "contact_name", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<String>,
    #[serde(rename = "contact_title", skip_serializing_if = "Option::is_none")]
    pub contact_title: Option<String>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl TimelineResponseTimelineInnerOneOf {
    /// Referral item
    pub fn new() -> TimelineResponseTimelineInnerOneOf {
        TimelineResponseTimelineInnerOneOf {
            id: None,
            feature_block: None,
            feature_block_id: None,
            start_timestamp: None,
            item_timestamp: None,
            service_description: None,
            service_name: None,
            contact_name: None,
            contact_title: None,
            memo: None,
            status: None,
        }
    }
}

