/*
 * PDX API
 *
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimelineItemCalendarEvent : A single timeline item representing a calendar event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimelineItemCalendarEvent {
    /// Type of feature block this timeline item belongs to
    #[serde(rename = "feature_block", skip_serializing_if = "Option::is_none")]
    pub feature_block: Option<String>,
    /// ID of the feature block
    #[serde(rename = "feature_block_id", skip_serializing_if = "Option::is_none")]
    pub feature_block_id: Option<i32>,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "created_timestamp", skip_serializing_if = "Option::is_none")]
    pub created_timestamp: Option<String>,
    #[serde(rename = "updated_timestamp", skip_serializing_if = "Option::is_none")]
    pub updated_timestamp: Option<String>,
    #[serde(rename = "external_uid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_uid: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<String>,
    #[serde(rename = "end_timestamp", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<String>,
    #[serde(rename = "organiser", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub organiser: Option<Option<String>>,
    #[serde(rename = "attendee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attendee: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    #[serde(rename = "trigger", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Option<String>>,
    #[serde(rename = "action", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub action: Option<Option<String>>,
    #[serde(rename = "reminder_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reminder_description: Option<Option<String>>,
    #[serde(rename = "duration_string", skip_serializing_if = "Option::is_none")]
    pub duration_string: Option<String>,
    #[serde(rename = "duration_of_event", skip_serializing_if = "Option::is_none")]
    pub duration_of_event: Option<f32>,
}

impl TimelineItemCalendarEvent {
    /// A single timeline item representing a calendar event
    pub fn new() -> TimelineItemCalendarEvent {
        TimelineItemCalendarEvent {
            feature_block: None,
            feature_block_id: None,
            instance: None,
            source: None,
            created_timestamp: None,
            updated_timestamp: None,
            external_uid: None,
            title: None,
            description: None,
            start_timestamp: None,
            end_timestamp: None,
            organiser: None,
            attendee: None,
            status: None,
            location: None,
            r#type: None,
            tags: None,
            trigger: None,
            action: None,
            reminder_description: None,
            duration_string: None,
            duration_of_event: None,
        }
    }
}

